version: '2'

services:
  mongo:
    image: bitnami/mongodb:4.4-debian-10
    container_name: crm_db
    ports: 
      - 27017:27017

  web:
    image: bitnami/node:13-debian-10
    container_name: crm_web
    entrypoint: ["npx", "next", "dev"]
    volumes: 
      - ./web:/app
    ports:
      - 3000:3000 
