version: '3.7'

services:
  mongo:
    image: mongo:4.0.20-xenial
    container_name: CRM_DB
    ports:
      - 27017:27017

  backend:
    build:
      context: ./backend
      target: development
    container_name: CRM_BACKEND
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    command: npm run start:dev
    depends_on:
      - mongo


  # web:
  #   build:
  #     context: ./web
  #     target: development
  #   container_name: crm_web
  #   command: npm run dev -p 8080
  #   volumes:
  #     - ./web:/usr/src/app
  #     - /usr/src/app/node_modules
  #   ports:
  #     - 8080:8080
  #   # depends_on:
    #   - backend
